default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

development:
  <<: *default
  host: db
  database: my_congratulations_development

test:
  <<: *default
  host: db
  database: my_congratulations_test

production:
  <<: *default
  database: my_congratulations_production
  username: my_congratulations
  password: <%= ENV['MY_CONGRATULATIONS_DATABASE_PASSWORD'] %>
