default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

development:
  <<: *default
  host: db
  database: take_a_train_development

test:
  <<: *default
  host: db
  database: take_a_train_test

production:
  <<: *default
  database: take_a_train_production
  username: take_a_train
  password: <%= ENV['TAKE_A_TRAIN_DATABASE_PASSWORD'] %>
